version: "3.7"
services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - server
  server:
    env_file: ./server/.env
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "6677:6677"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
